name: Telegram Bot Runner

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: "*/5 * * * *"
  workflow_dispatch: # для ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # бот работает 2 минуты и выключается
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python Bot.py
